version: "3"

services:
  buildmonitor:
    image: registry.gitlab.com/ets-devops/pipelines/digital-twin/build-monitor:latest
    container_name: build-monitor
    restart: always
    depends_on:
      - datastore
    ports:
      - 3000:3000
    volumes:
      - monitoring-data:/var/lib/grafana
    environment:
      - POSTGRES_HOST=datastore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=buildpulse
    labels:
      kompose.service.type: LoadBalancer

  buildpulse:
    image: registry.gitlab.com/ets-devops/pipelines/digital-twin/build-pulse:latest
    container_name: build-pulse
    restart: always
    depends_on:
      - datastore
      - broker
    ports:
      - 8000:8000
    env_file:
      - .env

  datasubscriber:
    image: registry.gitlab.com/ets-devops/pipelines/digital-twin/build-data-subscriber:latest
    container_name: build-data-subscriber
    restart: always
    depends_on:
      - broker
      - buildpulse
    environment:
      - PROJECT_NAME=template
      - MESSAGE_BROKER_URL=amqp://admin:password@broker:5672
      - MESSAGE_QUEUE_EXCHANGE=buildpulse
      - CBDT_API_BASE_URL=buildpulse:8000/api/v1

  datastore:
    image: postgres:17.0-alpine
    container_name: cbdt-datastore
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=buildpulse
    volumes:
      - cbdt-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10

  broker:
    image: rabbitmq:3.6-management-alpine
    container_name: cbdt-message-broker
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  cbdt-data:
  monitoring-data:
